# Generated by Django 6.0.2 on 2026-03-14 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_title', models.CharField(blank=True, default='', max_length=512)),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], db_index=True, default='movie', max_length=10)),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('en', 'English'), ('other', 'Other')], db_index=True, default='other', max_length=10)),
                ('poster_path', models.CharField(blank=True, default='', max_length=255)),
                ('backdrop_path', models.CharField(blank=True, default='', max_length=255)),
                ('overview', models.TextField(blank=True, default='')),
                ('tagline', models.CharField(blank=True, default='', max_length=512)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('vote_average', models.FloatField(db_index=True, default=0.0)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(db_index=True, default=0.0)),
                ('trailer_url', models.URLField(blank=True, default='', max_length=512)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'person',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('fearful', 'Fearful'), ('disgusted', 'Disgusted'), ('surprised', 'Surprised'), ('neutral', 'Neutral')], db_index=True, max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
            options={
                'verbose_name': 'Movie Genre',
                'verbose_name_plural': 'Movie Genres',
                'db_table': 'movie_genre',
                'ordering': ['movie__title', 'genre__name'],
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movie.MovieGenre', to='movie.genre'),
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Director', 'Director'), ('Music Director', 'Music Director'), ('Main Actor', 'Main Actor'), ('Main Actress', 'Main Actress'), ('Villain', 'Villain'), ('Comedian', 'Comedian')], max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='movie.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_roles', to='movie.person')),
            ],
            options={
                'verbose_name': 'Movie Crew Member',
                'verbose_name_plural': 'Movie Crew Members',
                'db_table': 'movie_crew',
                'ordering': ['movie__title', 'role', 'person__name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, default='')),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='movie.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['content_type', 'language'], name='movie_movie_content_d2dd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['content_type', 'popularity'], name='movie_movie_content_e8758a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('movie', 'person', 'role')},
        ),
    ]
