# Generated by Django 3.2.25 on 2024-12-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('rate', models.FloatField(default=0.0)),
                ('year', models.ImageField(upload_to='')),
            ],
        ),
    ]
