# Generated by Django 5.1.4 on 2024-12-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_title_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="casts",
            fields=[
                ("actor_id", models.AutoField(primary_key=True, serialize=False)),
                ("actor", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("debut_movie", models.TextField()),
                ("debut_year", models.IntegerField()),
                ("img", models.ImageField(upload_to="pics")),
            ],
            options={
                "db_table": "casts",
                "managed": False,
            },
        ),
    ]
