# Generated by Django 6.0.2 on 2026-03-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_emotionlog_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={'ordering': ['movie__title', 'genre__name'], 'verbose_name': 'Movie Genre', 'verbose_name_plural': 'Movie Genres'},
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='moviegenre',
            table='movie_genre',
        ),
    ]
