# Generated by Django 6.0.2 on 2026-03-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_genre_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='tmdb_id',
            new_name='id',
        ),
    ]
