# Generated by Django 5.1.4 on 2024-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_actees"),
    ]

    operations = [
        migrations.CreateModel(
            name="direct",
            fields=[
                ("director_id", models.AutoField(primary_key=True, serialize=False)),
                ("director", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("debut_movie", models.TextField()),
                ("debut_year", models.IntegerField()),
                ("img", models.ImageField(upload_to="pics")),
            ],
        ),
    ]
