# Generated by Django 5.1.4 on 2024-12-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_music"),
    ]

    operations = [
        migrations.CreateModel(
            name="sho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="pics")),
                ("rate", models.FloatField(default=0.0)),
                ("year_f", models.IntegerField()),
                ("ep", models.IntegerField()),
            ],
        ),
    ]
