# Generated by Django 5.1.4 on 2025-01-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_sho"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="director",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="genre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="title",
            name="watch_trailer",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
