# Generated by Django 5.1.4 on 2025-01-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0011_alter_title_director"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                db_column="actor_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.casts",
            ),
        ),
    ]
