# Generated by Django 5.1.4 on 2025-01-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_title_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="genre",
            fields=[
                ("genre_id", models.AutoField(primary_key=True, serialize=False)),
                ("genre", models.CharField(max_length=255)),
                ("img", models.ImageField(upload_to="pics")),
            ],
        ),
    ]
