# Generated by Django 5.1.4 on 2025-01-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0013_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="genre",
        ),
    ]
