# Generated by Django 5.1.4 on 2025-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0014_remove_title_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="genres",
            field=models.ManyToManyField(blank=True, to="movie.genre"),
        ),
    ]
