# Generated by Django 5.1.4 on 2025-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0015_title_genres"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieTitleGenres",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "movie_title_genres",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="title",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="movie.genre"
            ),
        ),
    ]
