# Generated by Django 5.1.4 on 2025-01-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0016_movietitlegenres_alter_title_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="sho",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sho",
            name="genre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sho",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sho",
            name="streaming_platform",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sho",
            name="trailer_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
